### ISSUE TITLE
Document Requirements for City of Greensboro Nonprofit Funding Process

### ISSUE THREAD

**Issue by marshallj** [codeforgso/committee-executive#23]

**Comment by alexzaleski1** [comment]
https://docs.google.com/a/codeforgreensboro.org/document/d/1qDNxM-7LDMBcVqey5TYTbceInayC05eAVAMH9-iCmWo/edit?usp=sharing

**Comment by marshallj** [comment]
Team decided not to pursue fro 2018. Revisit fro 2019.
